version: '3'

services:
  mysql:
    image: mariadb:10.1
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - db-data:/var/lib/mysql
  pdns:
    image: psitrax/powerdns
    entrypoint: >
      /entrypoint.sh
      --api=yes --api-key=pdnsapikey
      --webserver-address=0.0.0.0 --webserver-port=8081 --webserver-allow-from=0.0.0.0/0
    ports:
      - 8081:8081
  django:
    build: .
    ports:
      - 8000:8000
    environment:
      DINO_SECRET_KEY: 'secret'
      DINO_DEBUG: 'true'
      DINO_PDNS_APIURL: 'http://pdns:8081/api/v1'
      DINO_PDNS_APIKEY: 'pdnsapikey'

volumes:
  db-data:
